/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketse;

/**
 *
 * @author 20181041110020
 */
public class ComprarIngresso extends javax.swing.JDialog {

    /**
     * Creates new form ComprarIngresso
     */
    public ComprarIngresso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        textTitulo = new javax.swing.JTextField();
        quadradoEvento = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        textoData = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        textoHora = new javax.swing.JTextField();
        hora = new javax.swing.JLabel();
        textoLocal = new javax.swing.JTextField();
        local = new javax.swing.JLabel();
        preço = new javax.swing.JLabel();
        textTotalIngressos = new javax.swing.JTextField();
        caixaQntd = new javax.swing.JComboBox();
        quadradoIngresso1 = new javax.swing.JPanel();
        tituloIngresso = new javax.swing.JLabel();
        preçoIngresso = new javax.swing.JLabel();
        textNomeIngresso = new javax.swing.JTextField();
        textEmailIngresso = new javax.swing.JTextField();
        textCpfIngresso = new javax.swing.JTextField();
        nomeCampo = new javax.swing.JTextField();
        emailCampo = new javax.swing.JTextField();
        cpfCampo = new javax.swing.JTextField();
        pagarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textTitulo.setBackground(new java.awt.Color(240, 240, 240));
        textTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(0, 32, 144));
        textTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textTitulo.setText("COMPRAR INGRESSO");
        textTitulo.setBorder(null);

        quadradoEvento.setBackground(new java.awt.Color(255, 255, 255));
        quadradoEvento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 144)));

        titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo.setText("Título");

        descricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descricao.setForeground(new java.awt.Color(150, 149, 149));
        descricao.setText("A descrição do negócio aqui neste quadrado de texto enorme com um texto enorme.");

        textoData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoData.setForeground(new java.awt.Color(115, 115, 115));
        textoData.setText("Data:");
        textoData.setBorder(null);
        textoData.setOpaque(false);

        data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        data.setForeground(new java.awt.Color(115, 115, 115));
        data.setText("31/02/2019");

        textoHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoHora.setForeground(new java.awt.Color(115, 115, 115));
        textoHora.setText("Hora:");
        textoHora.setBorder(null);
        textoHora.setOpaque(false);

        hora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hora.setForeground(new java.awt.Color(115, 115, 115));
        hora.setText("25h");

        textoLocal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoLocal.setForeground(new java.awt.Color(115, 115, 115));
        textoLocal.setText("Local:");
        textoLocal.setBorder(null);
        textoLocal.setOpaque(false);

        local.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        local.setForeground(new java.awt.Color(115, 115, 115));
        local.setText("Casa");

        preço.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preço.setForeground(new java.awt.Color(0, 32, 144));
        preço.setText("jLabel1");

        javax.swing.GroupLayout quadradoEventoLayout = new javax.swing.GroupLayout(quadradoEvento);
        quadradoEvento.setLayout(quadradoEventoLayout);
        quadradoEventoLayout.setHorizontalGroup(
            quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEventoLayout.createSequentialGroup()
                        .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(local)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(preço))
                    .addGroup(quadradoEventoLayout.createSequentialGroup()
                        .addGroup(quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo)
                            .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        quadradoEventoLayout.setVerticalGroup(
            quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEventoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoEventoLayout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(quadradoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(data)
                            .addComponent(hora)
                            .addComponent(textoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(local)
                            .addComponent(textoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoEventoLayout.createSequentialGroup()
                        .addComponent(preço)
                        .addContainerGap())))
        );

        textTotalIngressos.setBackground(new java.awt.Color(240, 240, 240));
        textTotalIngressos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTotalIngressos.setText("Total de Ingressos:");
        textTotalIngressos.setBorder(null);
        textTotalIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalIngressosActionPerformed(evt);
            }
        });

        caixaQntd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caixaQntd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma quantidade", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        quadradoIngresso1.setBackground(new java.awt.Color(255, 255, 255));
        quadradoIngresso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 144)));

        tituloIngresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloIngresso.setForeground(new java.awt.Color(0, 32, 144));
        tituloIngresso.setText("INGRESSO 1");

        preçoIngresso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preçoIngresso.setForeground(new java.awt.Color(0, 32, 144));
        preçoIngresso.setText("jLabel1");

        textNomeIngresso.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textNomeIngresso.setForeground(new java.awt.Color(0, 32, 144));
        textNomeIngresso.setText("Nome");
        textNomeIngresso.setBorder(null);

        textEmailIngresso.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textEmailIngresso.setForeground(new java.awt.Color(0, 32, 144));
        textEmailIngresso.setText("E-mail");
        textEmailIngresso.setBorder(null);

        textCpfIngresso.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textCpfIngresso.setForeground(new java.awt.Color(0, 32, 144));
        textCpfIngresso.setText("CPF");
        textCpfIngresso.setBorder(null);

        nomeCampo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        emailCampo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        cpfCampo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout quadradoIngresso1Layout = new javax.swing.GroupLayout(quadradoIngresso1);
        quadradoIngresso1.setLayout(quadradoIngresso1Layout);
        quadradoIngresso1Layout.setHorizontalGroup(
            quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                        .addComponent(textCpfIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfCampo))
                    .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                        .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textEmailIngresso)
                            .addComponent(textNomeIngresso))
                        .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoIngresso1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(tituloIngresso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(preçoIngresso)
                .addContainerGap())
        );
        quadradoIngresso1Layout.setVerticalGroup(
            quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloIngresso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmailIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpfIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preçoIngresso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pagarBotao.setBackground(new java.awt.Color(71, 94, 176));
        pagarBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pagarBotao.setForeground(new java.awt.Color(255, 255, 255));
        pagarBotao.setText("PAGAR");
        pagarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTotalIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quadradoIngresso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textTitulo)
                            .addComponent(caixaQntd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quadradoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(pagarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(quadradoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(textTotalIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaQntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(quadradoIngresso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pagarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTotalIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalIngressosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalIngressosActionPerformed

    private void pagarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComprarIngresso dialog = new ComprarIngresso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox caixaQntd;
    private javax.swing.JTextField cpfCampo;
    private javax.swing.JLabel data;
    private javax.swing.JLabel descricao;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JLabel hora;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel local;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JButton pagarBotao;
    private javax.swing.JLabel preço;
    private javax.swing.JLabel preçoIngresso;
    private javax.swing.JPanel quadradoEvento;
    private javax.swing.JPanel quadradoIngresso1;
    private javax.swing.JTextField textCpfIngresso;
    private javax.swing.JTextField textEmailIngresso;
    private javax.swing.JTextField textNomeIngresso;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JTextField textTotalIngressos;
    private javax.swing.JTextField textoData;
    private javax.swing.JTextField textoHora;
    private javax.swing.JTextField textoLocal;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloIngresso;
    // End of variables declaration//GEN-END:variables
}
