/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketse;

/**
 *
 * @author 20181041110020
 */
public class ImprimirIngresso extends javax.swing.JDialog {

    /**
     * Creates new form ImprimirIngresso
     */
    public ImprimirIngresso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        quadradoIngresso1 = new javax.swing.JPanel();
        textNome1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        cpf1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        descricao1 = new javax.swing.JLabel();
        data1 = new javax.swing.JLabel();
        hora1 = new javax.swing.JLabel();
        local1 = new javax.swing.JLabel();
        preço = new javax.swing.JLabel();
        codigoDeBarras = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        textEmail1 = new javax.swing.JLabel();
        textCpf1 = new javax.swing.JLabel();
        email3 = new javax.swing.JLabel();
        data2 = new javax.swing.JLabel();
        textoHora1 = new javax.swing.JLabel();
        textoLocal1 = new javax.swing.JLabel();
        imprimirBotao = new javax.swing.JButton();
        baixarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketse/LOGO.png"))); // NOI18N

        quadradoIngresso1.setBackground(new java.awt.Color(255, 255, 255));
        quadradoIngresso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 144)));
        quadradoIngresso1.setPreferredSize(new java.awt.Dimension(70, 350));

        textNome1.setForeground(new java.awt.Color(0, 32, 144));
        textNome1.setText("Nome:");

        email1.setForeground(new java.awt.Color(0, 32, 144));
        email1.setText("jLabel1");

        cpf1.setForeground(new java.awt.Color(0, 32, 144));
        cpf1.setText("jLabel1");

        titulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo1.setText("Título");

        descricao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descricao1.setForeground(new java.awt.Color(150, 149, 149));
        descricao1.setText("A descrição do negócio aqui neste quadrado de texto enorme com um texto enorme.");

        data1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        data1.setForeground(new java.awt.Color(115, 115, 115));
        data1.setText("31/02/2019");

        hora1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hora1.setForeground(new java.awt.Color(115, 115, 115));
        hora1.setText("25h");

        local1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        local1.setForeground(new java.awt.Color(115, 115, 115));
        local1.setText("Casa");

        preço.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preço.setForeground(new java.awt.Color(0, 32, 144));
        preço.setText("jLabel1");

        codigoDeBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketse/Union.png"))); // NOI18N

        textEmail1.setForeground(new java.awt.Color(0, 32, 144));
        textEmail1.setText("E-mail:");

        textCpf1.setForeground(new java.awt.Color(0, 32, 144));
        textCpf1.setText("CPF:");

        email3.setForeground(new java.awt.Color(0, 32, 144));
        email3.setText("jLabel1");

        data2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        data2.setForeground(new java.awt.Color(115, 115, 115));
        data2.setText("Data:");

        textoHora1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoHora1.setForeground(new java.awt.Color(115, 115, 115));
        textoHora1.setText("Hora:");

        textoLocal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoLocal1.setForeground(new java.awt.Color(115, 115, 115));
        textoLocal1.setText("Local:");

        javax.swing.GroupLayout quadradoIngresso1Layout = new javax.swing.GroupLayout(quadradoIngresso1);
        quadradoIngresso1.setLayout(quadradoIngresso1Layout);
        quadradoIngresso1Layout.setHorizontalGroup(
            quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                        .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                                .addComponent(data2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(data1))
                            .addComponent(titulo1)
                            .addComponent(descricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNome1)
                                    .addComponent(textEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCpf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpf1)
                                    .addComponent(email1)
                                    .addComponent(email3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                        .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoHora1)
                            .addComponent(textoLocal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                                .addComponent(local1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(preço))
                            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                                .addComponent(hora1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(codigoDeBarras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quadradoIngresso1Layout.setVerticalGroup(
            quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoIngresso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(textEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf1)
                    .addComponent(textCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data1)
                    .addComponent(data2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora1)
                    .addComponent(textoHora1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preço)
                    .addGroup(quadradoIngresso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(local1)
                        .addComponent(textoLocal1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        imprimirBotao.setBackground(new java.awt.Color(71, 94, 176));
        imprimirBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imprimirBotao.setForeground(new java.awt.Color(255, 255, 255));
        imprimirBotao.setText("IMPRIMIR");
        imprimirBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBotaoActionPerformed(evt);
            }
        });

        baixarBotao.setBackground(new java.awt.Color(71, 94, 176));
        baixarBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        baixarBotao.setForeground(new java.awt.Color(255, 255, 255));
        baixarBotao.setText("BAIXAR");
        baixarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(quadradoIngresso1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(imprimirBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(baixarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quadradoIngresso1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baixarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baixarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixarBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baixarBotaoActionPerformed

    private void imprimirBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImprimirIngresso dialog = new ImprimirIngresso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baixarBotao;
    private javax.swing.JLabel codigoDeBarras;
    private javax.swing.JLabel cpf1;
    private javax.swing.JLabel data1;
    private javax.swing.JLabel data2;
    private javax.swing.JLabel descricao1;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel hora1;
    private javax.swing.JButton imprimirBotao;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel local1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel preço;
    private javax.swing.JPanel quadradoIngresso1;
    private javax.swing.JLabel textCpf1;
    private javax.swing.JLabel textEmail1;
    private javax.swing.JLabel textNome1;
    private javax.swing.JLabel textoHora1;
    private javax.swing.JLabel textoLocal1;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
