/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketse;

/**
 *
 * @author 20181042060030
 */
public class MeusEventos extends javax.swing.JDialog {

    /**
     * Creates new form MeusEventos
     */
    public MeusEventos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitulo = new javax.swing.JLabel();
        textBuscar = new javax.swing.JLabel();
        campoPesquisa = new javax.swing.JTextField();
        buscarBotao = new javax.swing.JButton();
        quadradoEvento1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        descricao1 = new javax.swing.JLabel();
        textCategoria1 = new javax.swing.JLabel();
        categoria1 = new javax.swing.JLabel();
        textData1 = new javax.swing.JLabel();
        data1 = new javax.swing.JLabel();
        textHora1 = new javax.swing.JLabel();
        hora1 = new javax.swing.JLabel();
        textLocal1 = new javax.swing.JLabel();
        local1 = new javax.swing.JLabel();
        ingressosVendidos1 = new javax.swing.JLabel();
        textIngressosVendidos1 = new javax.swing.JLabel();
        opcoesBotao1 = new javax.swing.JButton();
        quadradoEvento2 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        descricao2 = new javax.swing.JLabel();
        textCategoria2 = new javax.swing.JLabel();
        categoria2 = new javax.swing.JLabel();
        textData2 = new javax.swing.JLabel();
        data2 = new javax.swing.JLabel();
        textHora2 = new javax.swing.JLabel();
        hora2 = new javax.swing.JLabel();
        textLocal2 = new javax.swing.JLabel();
        local2 = new javax.swing.JLabel();
        opcoesBotao2 = new javax.swing.JButton();
        ingressosVendidos2 = new javax.swing.JLabel();
        textIngressosVendidos2 = new javax.swing.JLabel();
        quadradoEvento3 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        textCategoria3 = new javax.swing.JLabel();
        categoria3 = new javax.swing.JLabel();
        textData3 = new javax.swing.JLabel();
        data3 = new javax.swing.JLabel();
        textHora3 = new javax.swing.JLabel();
        hora3 = new javax.swing.JLabel();
        textLocal3 = new javax.swing.JLabel();
        local3 = new javax.swing.JLabel();
        ingressosVendidos3 = new javax.swing.JLabel();
        textIngressosVendidos3 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(0, 32, 144));
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("MEUS EVENTOS");

        textBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textBuscar.setText("Buscar Evento");

        campoPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 144)));
        campoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaActionPerformed(evt);
            }
        });

        buscarBotao.setBackground(new java.awt.Color(255, 255, 255));
        buscarBotao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buscarBotao.setForeground(new java.awt.Color(0, 32, 144));
        buscarBotao.setText("BUSCAR");
        buscarBotao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 144), 0));

        quadradoEvento1.setBackground(new java.awt.Color(255, 253, 253));

        titulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titulo1.setText("Título -");

        descricao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricao1.setText("A descrição do negócio aqui neste coisa...");

        textCategoria1.setForeground(new java.awt.Color(108, 104, 104));
        textCategoria1.setText("Categoria:");

        categoria1.setForeground(new java.awt.Color(108, 104, 104));
        categoria1.setText("jLabel12");

        textData1.setForeground(new java.awt.Color(108, 104, 104));
        textData1.setText("Data:");

        data1.setForeground(new java.awt.Color(108, 104, 104));
        data1.setText("31/02/2019");

        textHora1.setForeground(new java.awt.Color(108, 104, 104));
        textHora1.setText("Hora:");

        hora1.setForeground(new java.awt.Color(108, 104, 104));
        hora1.setText("25h");

        textLocal1.setForeground(new java.awt.Color(108, 104, 104));
        textLocal1.setText("Local:");

        local1.setForeground(new java.awt.Color(108, 104, 104));
        local1.setText("Casa");

        ingressosVendidos1.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        ingressosVendidos1.setForeground(new java.awt.Color(0, 32, 144));
        ingressosVendidos1.setText("25");

        textIngressosVendidos1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        textIngressosVendidos1.setForeground(new java.awt.Color(108, 104, 104));
        textIngressosVendidos1.setText("<html>INGRESSOS<br>VENDIDOS ");

        opcoesBotao1.setBackground(new java.awt.Color(255, 255, 255));
        opcoesBotao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketse/Pontinhos.png"))); // NOI18N
        opcoesBotao1.setBorderPainted(false);
        opcoesBotao1.setOpaque(false);

        javax.swing.GroupLayout quadradoEvento1Layout = new javax.swing.GroupLayout(quadradoEvento1);
        quadradoEvento1.setLayout(quadradoEvento1Layout);
        quadradoEvento1Layout.setHorizontalGroup(
            quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEvento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEvento1Layout.createSequentialGroup()
                        .addComponent(textData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data1))
                    .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(quadradoEvento1Layout.createSequentialGroup()
                            .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                    .addComponent(textLocal1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(local1))
                                .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                    .addComponent(textHora1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hora1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingressosVendidos1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textIngressosVendidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, quadradoEvento1Layout.createSequentialGroup()
                            .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                    .addComponent(titulo1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(descricao1))
                                .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                    .addComponent(textCategoria1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(categoria1)))
                            .addGap(116, 116, 116)
                            .addComponent(opcoesBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        quadradoEvento1Layout.setVerticalGroup(
            quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEvento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(quadradoEvento1Layout.createSequentialGroup()
                        .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descricao1)
                            .addComponent(titulo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria1))
                        .addGap(4, 4, 4)
                        .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                .addComponent(textData1)
                                .addGap(1, 1, 1)
                                .addComponent(textHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(textLocal1))
                            .addComponent(data1)
                            .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quadradoEvento1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(local1))))
                    .addGroup(quadradoEvento1Layout.createSequentialGroup()
                        .addComponent(opcoesBotao1)
                        .addGap(35, 35, 35)
                        .addGroup(quadradoEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIngressosVendidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingressosVendidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quadradoEvento2.setBackground(new java.awt.Color(255, 253, 253));

        titulo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titulo2.setText("Título -");

        descricao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricao2.setText("A descrição do negócio aqui neste coisa...");

        textCategoria2.setForeground(new java.awt.Color(108, 104, 104));
        textCategoria2.setText("Categoria:");

        categoria2.setForeground(new java.awt.Color(108, 104, 104));
        categoria2.setText("jLabel12");

        textData2.setForeground(new java.awt.Color(108, 104, 104));
        textData2.setText("Data:");

        data2.setForeground(new java.awt.Color(108, 104, 104));
        data2.setText("31/02/2019");

        textHora2.setForeground(new java.awt.Color(108, 104, 104));
        textHora2.setText("Hora:");

        hora2.setForeground(new java.awt.Color(108, 104, 104));
        hora2.setText("25h");

        textLocal2.setForeground(new java.awt.Color(108, 104, 104));
        textLocal2.setText("Local:");

        local2.setForeground(new java.awt.Color(108, 104, 104));
        local2.setText("Casa");

        opcoesBotao2.setBackground(new java.awt.Color(255, 255, 255));
        opcoesBotao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketse/Pontinhos.png"))); // NOI18N

        ingressosVendidos2.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        ingressosVendidos2.setForeground(new java.awt.Color(0, 32, 144));
        ingressosVendidos2.setText("25");

        textIngressosVendidos2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        textIngressosVendidos2.setForeground(new java.awt.Color(108, 104, 104));
        textIngressosVendidos2.setText("<html>INGRESSOS<br>VENDIDOS ");

        javax.swing.GroupLayout quadradoEvento2Layout = new javax.swing.GroupLayout(quadradoEvento2);
        quadradoEvento2.setLayout(quadradoEvento2Layout);
        quadradoEvento2Layout.setHorizontalGroup(
            quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEvento2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoEvento2Layout.createSequentialGroup()
                                .addComponent(textLocal2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(local2))
                            .addGroup(quadradoEvento2Layout.createSequentialGroup()
                                .addComponent(textHora2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hora2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingressosVendidos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIngressosVendidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addComponent(textData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data2))
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoEvento2Layout.createSequentialGroup()
                                .addComponent(textCategoria2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoria2))
                            .addGroup(quadradoEvento2Layout.createSequentialGroup()
                                .addComponent(titulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricao2)))
                        .addGap(116, 116, 116)
                        .addComponent(opcoesBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        quadradoEvento2Layout.setVerticalGroup(
            quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoEvento2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo2)
                            .addComponent(descricao2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria2)))
                    .addComponent(opcoesBotao2))
                .addGap(4, 4, 4)
                .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addComponent(textData2)
                        .addGap(1, 1, 1)
                        .addComponent(textHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textLocal2)
                            .addComponent(local2)))
                    .addComponent(data2)
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hora2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quadradoEvento2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(quadradoEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIngressosVendidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingressosVendidos2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        quadradoEvento3.setBackground(new java.awt.Color(255, 253, 253));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Título -");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("A descrição do negócio aqui neste coisa...");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketse/Pontinhos.png"))); // NOI18N

        textCategoria3.setForeground(new java.awt.Color(108, 104, 104));
        textCategoria3.setText("Categoria:");

        categoria3.setForeground(new java.awt.Color(108, 104, 104));
        categoria3.setText("jLabel12");

        textData3.setForeground(new java.awt.Color(108, 104, 104));
        textData3.setText("Data:");

        data3.setForeground(new java.awt.Color(108, 104, 104));
        data3.setText("31/02/2019");

        textHora3.setForeground(new java.awt.Color(108, 104, 104));
        textHora3.setText("Hora:");

        hora3.setForeground(new java.awt.Color(108, 104, 104));
        hora3.setText("25h");

        textLocal3.setForeground(new java.awt.Color(108, 104, 104));
        textLocal3.setText("Local:");

        local3.setForeground(new java.awt.Color(108, 104, 104));
        local3.setText("Casa");

        ingressosVendidos3.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        ingressosVendidos3.setForeground(new java.awt.Color(0, 32, 144));
        ingressosVendidos3.setText("25");

        textIngressosVendidos3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        textIngressosVendidos3.setForeground(new java.awt.Color(108, 104, 104));
        textIngressosVendidos3.setText("<html>INGRESSOS<br>VENDIDOS ");

        javax.swing.GroupLayout quadradoEvento3Layout = new javax.swing.GroupLayout(quadradoEvento3);
        quadradoEvento3.setLayout(quadradoEvento3Layout);
        quadradoEvento3Layout.setHorizontalGroup(
            quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoEvento3Layout.createSequentialGroup()
                        .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37))
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addComponent(textData3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(data3))
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addComponent(textCategoria3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoria3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quadradoEvento3Layout.createSequentialGroup()
                        .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addComponent(textLocal3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(local3))
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addComponent(textHora3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hora3)))
                        .addGap(275, 275, 275)
                        .addComponent(ingressosVendidos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIngressosVendidos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        quadradoEvento3Layout.setVerticalGroup(
            quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoEvento3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(quadradoEvento3Layout.createSequentialGroup()
                        .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria3))
                        .addGap(4, 4, 4)
                        .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(data3)
                            .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(hora3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textIngressosVendidos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ingressosVendidos3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(quadradoEvento3Layout.createSequentialGroup()
                                    .addComponent(textData3)
                                    .addGap(1, 1, 1)
                                    .addComponent(textHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addGroup(quadradoEvento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textLocal3)
                                        .addComponent(local3)))))))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBuscar)
                    .addComponent(quadradoEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(quadradoEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(quadradoEvento3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quadradoEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(quadradoEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(quadradoEvento3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeusEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeusEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeusEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeusEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MeusEventos dialog = new MeusEventos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBotao;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JLabel categoria1;
    private javax.swing.JLabel categoria2;
    private javax.swing.JLabel categoria3;
    private javax.swing.JLabel data1;
    private javax.swing.JLabel data2;
    private javax.swing.JLabel data3;
    private javax.swing.JLabel descricao1;
    private javax.swing.JLabel descricao2;
    private javax.swing.JLabel hora1;
    private javax.swing.JLabel hora2;
    private javax.swing.JLabel hora3;
    private javax.swing.JLabel ingressosVendidos1;
    private javax.swing.JLabel ingressosVendidos2;
    private javax.swing.JLabel ingressosVendidos3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel local1;
    private javax.swing.JLabel local2;
    private javax.swing.JLabel local3;
    private javax.swing.JButton opcoesBotao1;
    private javax.swing.JButton opcoesBotao2;
    private javax.swing.JPanel quadradoEvento1;
    private javax.swing.JPanel quadradoEvento2;
    private javax.swing.JPanel quadradoEvento3;
    private javax.swing.JLabel textBuscar;
    private javax.swing.JLabel textCategoria1;
    private javax.swing.JLabel textCategoria2;
    private javax.swing.JLabel textCategoria3;
    private javax.swing.JLabel textData1;
    private javax.swing.JLabel textData2;
    private javax.swing.JLabel textData3;
    private javax.swing.JLabel textHora1;
    private javax.swing.JLabel textHora2;
    private javax.swing.JLabel textHora3;
    private javax.swing.JLabel textIngressosVendidos1;
    private javax.swing.JLabel textIngressosVendidos2;
    private javax.swing.JLabel textIngressosVendidos3;
    private javax.swing.JLabel textLocal1;
    private javax.swing.JLabel textLocal2;
    private javax.swing.JLabel textLocal3;
    private javax.swing.JLabel textTitulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
